# Insert the following import line in alacritty.toml for
# gruvbox configuration

# import =
# ["/home/hmm/.config/alacritty/gruvbox-alacritty.toml",]

[colors.bright]
black   = "0x262626"
red     = "0xFB4934"
green   = "0xB8BB26"
yellow  = "0xFABD2F"
cyan    = "0x83A598"
magenta = "0xAD7FA8"
blue    = "0x3434E2"
white   = "0xEEEEEF"

[colors.normal]
black   = "0x282828"
red     = "0xCC3933"
green   = "0x98971A"
yellow  = "0xD79921"
cyan    = "0x458588"
magenta = "0x75507B"
blue    = "0x06989A"
white   = "0xD3D7CF"

[colors.primary]
background = "0x151515"
foreground = "0xe2e2e2"
