#!/bin/sh

# Exit if any errors ...
set -e

if [ -z "$(which alacritty)" -o -z "$(which alacritty)" ];
then
	echo "Warning, Seems like you don't have alacritty install
	properly."
else
	if [ ! -e "$HOME/.config/alacritty/gruvbox-alacritty.toml" ];
	then
		mkdir -p "$HOME/.config/alacritty"
	fi
	ln -sf "$PWD/gruvbox-alacritty.toml" "$HOME/.config/alacritty/gruvbox-alacritty.toml"
fi
